// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a15f08332763d2e41d9787cec4e8324c9e5870dc/content-type/content-type.d.ts
declare module ContentType {
    interface StaticFunctions {
        parse(string: string): MediaType;
        parse(req: { headers: any; }): MediaType;
        parse(res: { getHeader(key: string): string; }): MediaType;
        format(obj: MediaType): string;
    }

    interface MediaType {
        type: string;
        parameters?: any;
    }
}

declare module "content-type" {
    var x: ContentType.StaticFunctions;
    export = x;
}
