// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/3aac49ea7ee2e6d15d3dcbc45f4e6bb0af544517/nodemailer-ses-transport/nodemailer-ses-transport.d.ts
declare module "nodemailer-ses-transport" {

	import * as AWS from 'aws-sdk';

	namespace sesTransport {
		export interface SesOptions {
			ses?: AWS.SES;
			accessKeyId?: string;
			secretAccessKey?: string;
			sessionToken?: string;
			region?: string;
			httpOptions?: AWS.HttpOptions;
			rateLimit?: number;
			maxConnections?: number;
		}
	}

	function sesTransport(options: sesTransport.SesOptions): nodemailer.Transport;

	export = sesTransport;
}
