// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/statuses/statuses.d.ts
declare module 'statuses' {
    interface Status {
        [code: number]: string;
        [msg: string]: any | number;

        codes: Array<number>;
        redirect: {[code: number]: boolean};
        empty: {[code: number]: boolean};
        retry: {[code: number]: boolean};

        (code: number | string): number;
    }

    var status: Status;
    export = status;
}
